var quotes = [
    `"Today’s goals: Coffee and kindness. Maybe two coffees, and then kindness." – Nanea Hoffman`,
    `"Act as if what you do makes a difference. It does." – William James`,
    `"Success is not final, failure is not fatal: it is the courage to continue that counts." – Winston Churchill`,
    `"Never bend your head. Always hold it high. Look the world straight in the eye." – Helen Keller`,
    `"What you get by achieving your goals is not as important as what you become by achieving your goals." – Zig Ziglar`,
    `"Believe you can and you're halfway there." – Theodore Roosevelt`,
    `"When you have a dream, you've got to grab it and never let go." – Carol Burnett`,
    `"I can't change the direction of the wind, but I can adjust my sails to always reach my destination." – Jimmy Dean`,
    `"No matter what you're going through, there's a light at the end of the tunnel." – Demi Lovato`,
    `"You do not find the happy life. You make it." – Camilla Eyring Kimball`,
    `"Life is like riding a bicycle. To keep your balance, you must keep moving." – Albert Einstein`,
    `"Try to be a rainbow in someone else's cloud." – Maya Angelou`,
    `"Limit your 'always' and your 'nevers.' – Amy Poehler​​`,
    `"Nothing is impossible. The word itself says 'I'm possible!'" – Audrey Hepburn`,
    `"You are never too old to set another goal or to dream a new dream." – C.S. Lewis`,
    `"Everyone should believe in something. I believe I will have another coffee." – Unknown`,
    `"I never drink coffee at lunch. I find it keeps me awake for the afternoon." – Ronald Reagan`,
    `"Coffee first. Schemes later." – Leanna Renee Hieber`,
    `"But even a bad cup of coffee is better than no coffee at all." – David Lynch`,
    `"Caffeine and sugar, the two basic food groups." – Laurell K. Hamilton`,
    `"It’s amazing how the world begins to change through the eyes of a cup of coffee." – Donna A. Favors`,
    `"Confidence is 10 percent hard work and 90 percent delusion." – Tina Fey`,
    `"If not me, who? If not now, when?" – Emma Watson`,
    `"Doubt is a killer. You just have to know who you are and what you stand for." – Jennifer Lopez`,
    `"Whether you think you can or you think you can’t, you’re right." – Henry Ford`,
    `"The best revenge is massive success." – Frank Sinatra`,
    `"The difference between winning and losing is, most often, not quitting." – Walt Disney`,
    `"To get the full value of joy you must have someone to divide it with." – Mark Twain`,
    `"Scatter joy!" – Ralph Waldo Emerson`,
    `"To serve is beautiful, but only if it is done with joy and a whole heart and a free mind." – Pearl S. Buck`,
    `"Who you are is defined by what you’re willing to struggle for." – Mark Manson`,
    `"To be happy we need something to solve. Happiness is therefore a form of action;" – Mark Manson`,
    `"Don’t just sit there. Do something. The answers will follow." – Mark Manson`,
]
    //`"" – `,